version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=system123#
      - SECRET_KEY=changeme
      - ALLOWED_HOSTS=127.0.0.1
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=system123#


  proxy:
    build: 
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static


volumes:
  postgres-data:
  static-data: